name: project-mssqlserver-2019
services:
  db:
    # build: .
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file: .env
    ports:
      - "1434:1433"
    restart: always
    command: /bin/bash ./entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S mssql-server -U sa -P ${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s
    networks:
      network-db:
        priority: 0
    volumes:
      - mssql-data:/var/opt/mssql/
      - ./entrypoint.sh:/entrypoint.sh
      - ./configure-db.sh:/configure-db.sh
      - ./db/setup.sql:/db/setup-db.sql
networks:
    network-db:
      name: network-db
      driver: bridge
volumes:
    mssql-data:
      name: mssql-data